version: '3.8'
name : meltianov_test_service

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/meltianov_test_service/src
      - ./requirements.txt:/meltianov_test_service/requirements.txt
      - ./.env:/meltianov_test_service/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis